# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the Spanish version of the site.
[es]
  baseURL = "https://fisiquimicamente.com/"
  languageCode = "es"
  contentDir = "content/es"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.  
  
[en]
  baseURL = "https://physichemically.com/"
  languageCode = "en"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title = "PhysiChemically"

  [en.permalinks]
    authors = "/author/:slug/"
    tags = "/tag/:slug/"
    categories = "/category/:slug/"
    publication_types = "/publication-type/:slug/"
    post = "/blog/:year/:month/:day/:slug"
  [en.params]    
    [en.params.marketing.seo]
      org_name = "PhysiChemically"
  	  description = "Physics and Chemistry Resources, Tutorials and Current Science"
      # address = {region = "Cantabria", country = "Spain", country_code = "ES"}

[ca]
  baseURL = "https://fisiquimicament.com/"
  languageCode = "ca"
  contentDir = "content/ca"
  title = "FisiQuímicament"
  [ca.params]    
    [ca.params.marketing.seo]
      org_name = "FisiQuímicament"
      description = "Recursos de Física i Química, tutorials i ciència d'actualitat"
      # address = {region = "Cantabria", country = "Espanya", country_code = "ES"}

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
