# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "📚 Notes"
  url = "notes/"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "13-14 year-olds"
  url = "notes/#segundo-eso"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "14-15 year-olds"
  url = "notes/#tercero-eso"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "15-16 year-olds"
  url = "notes/#cuarto-eso"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "16-17 year-olds"
  url = "notes/#primero-bach"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "17-18 year-olds Physics"
  url = "notes/#segundo-bach-fisica"
  parent = "apuntes"
  weight = 5
  
[[main]]
  name = "17-18 year-olds Chemistry"
  url = "notes/#segundo-bach-quimica"
  parent = "apuntes"
  weight = 6  
  
[[main]]
  name = "IUPAC Nomenclature"
  url = "notes/#formulacion-nomenclatura-iupac"
  parent = "apuntes"
  weight = 7  
  
[[main]]
  name = "🎓 EBAU resources"
  url = "ebau-resources/"
  identifier = "recursos-ebau"
  weight = 2
  
[[main]]
  name = "☢️ Physics"
  url = "ebau-resources/#examenes-fisica"
  parent = "recursos-ebau"
  weight = 1
  
[[main]]
  name = "⚗️ Chemistry"
  url = "ebau-resources/#examenes-quimica"
  parent = "recursos-ebau"
  weight = 2  
  
[[main]]
  name = "💡 Tips"
  url = "ebau-resources/#consejos"
  parent = "recursos-ebau"
  weight = 3  

[[main]]
  name = "👐 Tutorials"
  url = "tutoriales/"
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentation of information"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "🔗 Interesting links"
  url = "interesting-links/"  
  identifier = "enlaces-interes"
  weight = 4  

[[main]]
  name = "🗞️ News"
  url = "#novedades"
  identifier = "novedades"
  weight = 5

[[main]]
  name = "Twitter"
  url = "#novedades"
  parent = "novedades"
  weight = 1  
  
[[main]]
  name = "💬 Blog"
  url = "/post"
  parent = "novedades"
  weight = 2    

[[main]]
  name = "👨‍🔬 About me"
  url = "sobre-mi/"
  identifier = "sobre-mi"
  weight = 6
  
[[main]]
  name = "👨‍🔬 Interests and education"
  url = "sobre-mi/"
  parent = "sobre-mi"
  weight = 1

[[main]]
  name = "👣 Career path"
  url = "sobre-mi/#trayectoria-profesional"
  parent = "sobre-mi"
  weight = 2  
  
[[main]]
  name = "✈️ Research stays"
  url = "sobre-mi/#estancias-investigacion"
  parent = "sobre-mi"
  weight = 3

[[main]]
  name = "✉️ Contact"
  url = "#contacto"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
