# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "⚛️ Recursos FiQ"
  url = "recursos-fisica-quimica/"
  identifier = "recursos-fiq"
  weight = 1
  
[[main]]
  name = "📚 Apunts"
  url = "recursos-fisica-quimica/apunts"
  parent = "recursos-fiq"
  weight = 1

[[main]]
  name = "🎓 PBAU"
  url = "recursos-fisica-quimica/pbau"
  parent = "recursos-fiq"
  weight = 2  

[[main]]
  name = "👐🏼 Tutorials"
  url = "tutorials/"  
  identifier = "tutorials"
  weight = 2
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutorials"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "Presentació d'informació"
  parent = "tutorials"
  url = "tutorials/presentacio-informacio"
  weight = 2    

[[main]]
  name = "🔗 Recursos online"
  url = "recursos-online/"
  identifier = "recursos-online"
  weight = 4 

[[main]]
  name = "🗞️ Novetats"
  url = "#novetats"
  identifier = "novetats"
  weight = 4

[[main]]
  name = "Twitter"
  url = "#novetats"
  parent = "novetats"
  weight = 1  
  pre = "<i class='fab fa-twitter mr-1'></i>"  
  
[[main]]
  name = "✍🏼 Blog"
  url = "/post"
  parent = "novetats"
  weight = 2    

[[main]]
  name = "👥 Equip"
  url = "equip/"
  identifier = "equip"
  weight = 5   

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
