# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "📚 Notes"
  url = "notes/"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "13-14 year-olds"
  url = "notes/#13-14-year-olds"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "14-15 year-olds"
  url = "notes/#14-15-year-olds"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "15-16 year-olds"
  url = "notes/#15-16-year-olds"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "16-17 year-olds"
  url = "notes/#16-17-year-olds"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "17-18 year-olds Physics"
  url = "notes/#17-18-year-olds-physics"
  parent = "apuntes"
  weight = 5
  
[[main]]
  name = "17-18 year-olds Chemistry"
  url = "notes/#17-18-year-olds-chemistry"
  parent = "apuntes"
  weight = 6  
  
[[main]]
  name = "Nomenclature of Chemistry"
  url = "notes/#nomenclature-chemistry"
  parent = "apuntes"
  weight = 7  
  
[[main]]
  name = "🎓 EBAU Resources"
  url = "ebau-resources/"
  identifier = "recursos-ebau"
  weight = 2
  
[[main]]
  name = "☢️ Physics"
  url = "ebau-resources/#physics"
  parent = "recursos-ebau"
  weight = 1
  
[[main]]
  name = "⚗️ Chemistry"
  url = "ebau-resources/#chemistry"
  parent = "recursos-ebau"
  weight = 2  
  
[[main]]
  name = "💡 Tips"
  url = "ebau-resources/#tips"
  parent = "recursos-ebau"
  weight = 3  

[[main]]
  name = "👐 Tutorials"
  url = "tutorials/"
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "Presentation of Information"
  parent = "tutoriales"
  url = "tutorials/presentation-information"
  weight = 2    

[[main]]
  name = "🔗 Online Resources"
  url = "online-resources/"
  identifier = "enlaces-interes"
  weight = 4  

[[main]]
  name = "🗞️ News"
  url = "#news"
  identifier = "news"
  weight = 5

[[main]]
  name = "Twitter"
  url = "#news"
  parent = "news"
  weight = 1  
  
[[main]]
  name = "💬 Blog"
  url = "/post"
  parent = "news"
  weight = 2    

[[main]]
  name = "👨‍🔬 About me"
  url = "about-me/"
  identifier = "sobre-mi"
  weight = 6
  
[[main]]
  name = "👨‍🔬 Interests and Education"
  url = "about-me/"
  parent = "sobre-mi"
  weight = 1

[[main]]
  name = "👣 Career Path"
  url = "about-me/#career-path"
  parent = "sobre-mi"
  weight = 2  
  
[[main]]
  name = "✈️ Research Stays"
  url = "about-me/#research-stays"
  parent = "sobre-mi"
  weight = 3

[[main]]
  name = "✉️ Contact"
  url = "#contact"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
