# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "⚛️ Recursos FyQ"
  url = "recursos-fisica-quimica/"
  identifier = "recursos-fyq"
  weight = 1
  
[[main]]
  name = "📚 Apuntes"
  url = "recursos-fisica-quimica/apuntes"
  parent = "recursos-fyq"
  weight = 1

[[main]]
  name = "🎓 EBAU"
  url = "recursos-fisica-quimica/ebau"
  parent = "recursos-fyq"
  weight = 2
  
[[main]]
  name = "📝 Oposiciones"
  url = "recursos-fisica-quimica/oposiciones"
  parent = "recursos-fyq"
  weight = 3

[[main]]
  name = "👐🏼 Tutoriales"
  url = "tutoriales/"  
  identifier = "tutoriales"
  weight = 2
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentación de información"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "🔗 Enlaces de interés"
  url = "enlaces-interes/"  
  identifier = "enlaces-interes"
  weight = 3
  
[[main]]
  name = "💻 Recursos online"
  url = "enlaces-interes/recursos-online"
  parent = "enlaces-interes"
  weight = 1
  
[[main]]
  name = "🤗 Páginas amigas"
  url = "enlaces-interes/paginas-amigas"
  parent = "enlaces-interes"
  weight = 2

# [[main]]
#   name = "🗞️ Novedades"
#   url = "#novedades"
#   identifier = "novedades"
#   weight = 4

# [[main]]
#   name = "Twitter"
#   url = "#novedades"
#   parent = "novedades"
#   weight = 1  
#   pre = "<i class='fab fa-twitter mr-1'></i>"  
  
# [[main]]
#   name = "✍🏼 Blog"
#   url = "/post"
#   parent = "novedades"
#   weight = 2

[[main]]
  name = "✍🏼 Blog"
  url = "/post"
  weight = 4

[[main]]
  name = "👥 Equipo"
  url = "equipo/"
  identifier = "equipo"
  weight = 5   

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
