# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/customization/
# Documentation: https://wowchemy.com/docs/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[search]`).

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/media/` folder and specify image name here.
sharing_image = "sharing.png"
sharing_image_en = "sharing-en.png"
sharing_image_ca = "sharing-ca.png"

############################
## Advanced
############################

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length = 135

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = ["footnotes"]

[appearance]
  theme_day = "nord"
  theme_night = "nord"
  font = "garamond"
  font_size = "XL"

[header]
  [header.navbar]
    enable = true
    align = "l"
    show_logo = true
    highlight_active_link = false
    show_language = false
    show_day_night = true
    show_translations = true

# Translations in footer
[footer]
  show_translations = true
  text = "&copy; 2020&ndash;2022 Rodrigo Alcaraz de la Osa"
  [footer.copyright]
    notice = ""
    [footer.copyright.license]
      enable = false
      allow_derivatives = true
      share_alike = true
      allow_commercial = true

[features]
  [features.syntax_highlighter]
    enable = true
    extra_languages = ["latex"]  # Add support for highlighting additional languages
    theme = "nord"

  [features.math]
    enable = true

  [features.diagram]
    enable = false

  [features.avatar]  
    gravatar = false
    shape = "circle"

  [features.privacy_pack]
    enable = true

  [features.comment]
    provider = "discord"    
  
  [features.map]  
    provider = ""
    api_key = ""
    zoom = 15

  [features.search]  
    provider = "wowchemy"
  
    [features.search.algolia]
      app_id = ""
      api_key = ""
      index_name = ""
      show_logo = false      

[locale]
  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "15:04"

  # Address format.
  address_format = "es"

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Marketing
############################
[marketing]
  [marketing.seo]
    site_type = "Project"
    local_business_type = ""
    org_name = "FisiQuímicamente"
    description = "Recursos de Física y Química, tutoriales y ciencia de actualidad"
    twitter = "fqmente"
    phone = ""
    # address = {region = "Cantabria", country = "España", country_code = "ES"}
    coordinates = {latitude = "43.416645", longitude = "-4.041206"}

  [marketing.analytics]
    google_analytics = ""
    google_tag_manager = ""

############################
## Icon Pack Extensions
############################
[extensions]

  [extensions.cms]
    netlify_cms = true
    publish_mode = "editorial_workflow"      

  [extensions.academicons]
    enable = false  # Academicons icon pack https://jpswalsh.github.io/academicons/

  [extensions.isotope]
    enable = true
