[build]
  command = "hugo --gc --minify -b $URL"

[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENABLEGITINFO = "true"  

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "rodrigoalcarazdelaosa.me/*"
  to = "https://fisiquimicamente.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "rodrigoalcarazdelaosa.me/apuntes-formulacion-nomenclatura-quimica/organica/*"
  to = "/recursos-fisica-quimica/apuntes/formulacion-nomenclatura-quimica/organica/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/en/*"
  to = "https://physichemically.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ca/*"
  to = "https://fisiquimicament.com/:splat"
  status = 301
  force = true  

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true    