name: Publish to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        include:
          - projectName: 'fisiquimicamente'
            directory: 'public/es'
            PDFEmbedKey: ${{ secrets.PDF_EMBED_API_KEY_ES }}
          - projectName: 'physichemically'
            directory: 'public/en'
            PDFEmbedKey: ${{ secrets.PDF_EMBED_API_KEY_EN }}
          - projectName: 'fisiquimicament'
            directory: 'public/ca'
            PDFEmbedKey: ${{ secrets.PDF_EMBED_API_KEY_CA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Fetch **all** history (not just deploy commit) for Hugo's .GitInfo and .Lastmod
          # See https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - name: Download Hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        # 0.103.0 began new naming convention
        env:
          HUGO_VERSION: 0.111.3 # will get Extended Version below
      - name: Install Hugo
        run: sudo dpkg -i hugo*.deb
      - name: Build site with Hugo
        run: source get_last_commit_hash.sh && hugo --gc --minify
        env:                   
          HUGOxPARAMSxPDF_EMBED_API_KEY: ${{ matrix.PDFEmbedKey }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.projectName }}
          directory: ${{ matrix.directory }}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}